### ISSUE TITLE
Event for when items are rearranged

### ISSUE THREAD

**Issue by seertenedos** [WAELKASSEM/DragDropBlazor#1]
It would be great if there was an event when you drag an item to say what item was dragged to which index. I need this to stream the changes to the backend where i don't want to send the whole list every time a user moves an item.

**Comment by WAELKASSEM** [comment]
OnItemAdded (Event Callback): Event Callback with last added item as argument. Modifying the List from outside the component isn't checked.

Have you tried using this callback to get the item's index , it also has the item as argument?

you can use it to search the list.

**Comment by WAELKASSEM** [comment]
I'll see what I can do, during next weekend.

**Comment by WAELKASSEM** [comment]
what about having 2 indices : x and y , denoting that an item has been moved from x to y ? 
would you be more comfortable with that ?

**Comment by seertenedos** [comment]
Yes that would work for me. I am also testing another control now that does
that.

**Comment by WAELKASSEM** [comment]
Done.
